firstName = input("Please enter your first name:")
lastName = input("Please enter your last name:")
fullName = firstName + ' ' + lastName
print("Your full name is ", fullName.upper())
print("Your initials are", firstName[0].capitalize(), lastName[0].capitalize())
lenFirstName = len(firstName)
print("First name length is",lenFirstName,"letters")
lenLastName = len(lastName)
print("Last name length is",lenLastName,"letters")
lenFullName = len(fullName)
print("Full name length is", lenFirstName+lenLastName, "letters")
print("First name starts with", firstName[0].upper())
print("First name ends with", firstName[-1].upper())
print("Last name starts with", lastName[0].upper())
print("Last name ends with", lastName[-1].upper())
print("First name indexes are 0 -",lenFirstName-1)
print("Last name indexes are 0 -",lenLastName-1)
print("First name trims 1",firstName[0:3].capitalize())
print("First name trims 2",firstName[1:])
print("Last name trims 1",lastName[0:3].capitalize())
print("Last name trims 2",lastName[3:])

